---
apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  name: 00d03114-0000-0000-0000-e45f0135fbb2
  labels:
    metal.sidero.dev/serverclass: rpi.8gb
    metal.sidero.dev/machine.type: controlplane
spec:
  accepted: false
  hostname: k3s-node0.lab
  pxeBootAlways: true
  environmentRef:
    namespace: default
    name: rpi4-beta
  system:
    manufacturer: Raspberry Pi Foundation
    productName: Raspberry Pi 4 Model B
    version: D03114
    serialNumber: "0000E45F0135FBB2"
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/mmcblk0
    - op: add
      path: /machine/sysctls
      value:
        kernel.kexec_load_disabled: 1
