---
apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  name: 03000200-0400-0500-0006-000700080009
  labels:
    metal.sidero.dev/serverclass: trigkey
    metal.sidero.dev/machine.type: controlplane
spec:
  accepted: false
  hostname: k3s-master.lab
  environmentRef:
    name: agent-amd64-beta
  system:
    manufacturer: AZW
    productName: S5
    version: Default string
    serialNumber: Default string
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/nvme0n1
