apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  name: 00d03114-0000-0000-0000-e45f01496f26
  labels:
    metal.sidero.dev/serverclass: rpi.8gb
spec:
  accepted: true
  hostname: k3s-node3.lab
  system:
    manufacturer: Raspberry Pi Foundation
    productName: Raspberry Pi 4 Model B
    version: D03114
    serialNumber: "0000E45F01496F26"
