apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  name: 03000200-0400-0500-0006-000700080009
  labels:
    metal.sidero.dev/serverclass: trigkey
spec:
  accepted: true
  hostname: k3s-master.lab
  system:
    manufacturer: AZW
    productName: S5
    version: Default string
    serialNumber: "Default string"
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/nvme0n1
    - op: replace
      path: /machine/install/extraKernelArgs
      value:
        - panic=0
