---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: rpi.8gb
spec:
  environmentRef:
    namespace: default
    name: rpi4
  qualifiers:
    systemInformation:
      - manufacturer: Raspberry Pi Foundation
        productName: Raspberry Pi 4 Model B
        version: D03114
  bootFromDiskMethod: ipxe-sanboot
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/mmcblk0
    - op: add
      path: /machine/sysctls
      value:
        kernel.kexec_load_disabled: 1
