---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: rpi.8gb
spec:
  selector:
    matchLabels:
      metal.sidero.dev/serverclass: rpi.8gb
  qualifiers:
    systemInformation:
      - manufacturer: Raspberry Pi Foundation
        productName: Raspberry Pi 4 Model B
        version: D03115
  environmentRef:
    name: rpi4
  bootFromDiskMethod: ipxe-sanboot
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/mmcblk0
    - op: add
      path: /machine/sysctls
      value:
        kernel.kexec_load_disabled: 1
