---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: trigkey
spec:
  selector:
    matchLabels:
      metal.sidero.dev/serverclass: trigkey
  qualifiers:
    systemInformation:
      - manufacturer: AZW
        productName: S5
        version: Default string
  bootFromDiskMethod: ipxe-sanboot
  environmentRef:
    name: agent-amd64-beta
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/nvme0n1
