---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: trigkey
spec:
  selector:
    matchLabels:
      metal.sidero.dev/serverclass: trigkey
  qualifiers:
    cpu:
      - manufacturer: Advanced Micro Devices, Inc.
        version: AMD Ryzen 5 5560U with Radeon Graphics
    systemInformation:
      - manufacturer: AZW
        productName: S5
  environmentRef:
    name: agent-amd64-beta
