---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: pk8s-workers
  namespace: sidero-system
spec:
  template:
    spec:
      generateType: join
      talosVersion: v1.3.0-beta.2
      configPatches:
        - op: add
          path: /machine/install/extensions
          value:
            - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
