---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.enc.yaml
  - namespaces.yaml
  - helm-release.yaml
configMapGenerator:
  - name: zfs-iscsi-values
    namespace: democratic-csi
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml
