---
apiVersion: metal.sidero.dev/v1alpha1
kind: Environment
metadata:
  name: agent-amd64
spec:
  initrd:
    url: https://github.com/siderolabs/talos/releases/download/v1.3.0/initramfs-amd64.xz
    sha512: 3e48e10dde191bf63b499af73d7857405d91bb10bf8ffc4482492dea737648034f89eb8d62aed268d1a890f49c1fd9f27c27a397e0f872062b048534b3b23df4
  kernel:
    url: https://github.com/siderolabs/talos/releases/download/v1.3.0/vmlinuz-amd64
    sha512: 463e7ee4427de400ea1f4e3eff75c18014a0198a04af5bd44b637705a595401fd3c13eeb677fdb6470c6820c172581d6010f826f6ffbda93ebd8338436513c24
    args:
      - console=tty0
      - console=ttyS0
      - consoleblank=0
      - earlyprintk=ttyS0
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - random.trust_cpu=on
      - slab_nomerge=
      - panic=0
      - talos.platform=metal
